[package]
name = "ensure-hosts-have-env-tags"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "*"
failure = "*"